In [1]:
import pandas as pd
import os
os.chdir('/home/s3/hyeryung/mucoco')

In [3]:
outputs=pd.read_json('outputs/toxicity/roberta-base-jigsaw-toxicity-classifier-with-gpt2-large-embeds-energy-training/gbi-word-netps3-nls1-os20-es4-allsat-toxic-to-nontoxic-attention-kf1j15xk/outputs_epsilon-3.txt',
            lines=True)

In [110]:
origin=pd.read_json('new_module/data/toxicity-avoidance/testset_gpt2_2500.jsonl', lines=True)

## unravel
origin=origin.explode('generations')

origin.shape

origin['prompt']=origin['prompt'].apply(lambda x: x['text'])

origin['text']=origin['generations'].apply(lambda x: x['text'])

gen_dict=origin['generations'].values[0]

for col in gen_dict.keys():
    origin[col] = origin['generations'].apply(lambda x: x[col])

origin=origin.reset_index(drop=True)

origin=origin.rename(columns={'text':'origin_text', 'tokens':'origin_tokens'})

In [4]:
## unravel
outputs=outputs.explode('generations')

outputs.shape

outputs['prompt']=outputs['prompt'].apply(lambda x: x['text'])

outputs['text']=outputs['generations'].apply(lambda x: x['text'])

gen_dict=outputs['generations'].values[0]

for col in gen_dict.keys():
    outputs[col] = outputs['generations'].apply(lambda x: x[col])

In [12]:
outputs=outputs.reset_index(drop=True)

In [17]:
outputs=pd.concat([outputs, origin[['origin_text']]], axis=1)

In [20]:
outputs.loc[outputs['text']=='','text']=outputs.loc[outputs['text']=='','origin_text']

In [22]:
outputs.loc[outputs['weighted_loss']==-1,]

,prompt,generations,text,tokens,allsat,losses,weighted_loss,repeat_count,mucoco,origin_text
464,"According to the criminal complaint, Edah kick...","{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
468,"According to the criminal complaint, Edah kick...","{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
469,"According to the criminal complaint, Edah kick...","{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
511,An advertisement for the product shows a girl ...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
519,An advertisement for the product shows a girl ...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
701,Cruz began by mocking Trump’s reputation for i...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
919,"Behold, My Little Deathwing: Ponywing ...","{'text': '', 'tokens': [], 'allsat': False, 'l...",<|endoftext|>,[],False,-1,-1.0,-1,True,<|endoftext|>
1341,The lawsuits dispute Airbnb's assertion that i...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
1343,The lawsuits dispute Airbnb's assertion that i...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
1670,Dotan says the bridge will serve as a runway f...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.<|endoftext|>,[],False,-1,-1.0,-1,True,.<|endoftext|>
2234,And for those of you who are happily and comfo...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.

In [97]:
outputs=pd.read_json('outputs/toxicity/roberta-base-jigsaw-toxicity-classifier-with-gpt2-large-embeds/gbi-word-netps3-nls1-os20-es4-allsat-toxic-to-nontoxic-attention-kut5whdo/outputs_epsilon-3.txt',
            lines=True)

In [98]:
## unravel
outputs=outputs.explode('generations')

outputs.shape

outputs['prompt']=outputs['prompt'].apply(lambda x: x['text'])

outputs['text']=outputs['generations'].apply(lambda x: x['text'])

gen_dict=outputs['generations'].values[0]

for col in gen_dict.keys():
    outputs[col] = outputs['generations'].apply(lambda x: x[col])

In [99]:
outputs=outputs.reset_index(drop=True)

In [100]:
outputs=pd.concat([outputs, origin[['origin_text']]], axis=1)

In [101]:
outputs.loc[outputs['text']=='','text']=outputs.loc[outputs['text']=='','origin_text']

In [102]:
outputs.loc[outputs['weighted_loss']==-1,]

,prompt,generations,text,tokens,allsat,losses,weighted_loss,repeat_count,mucoco,origin_text
464,"According to the criminal complaint, Edah kick...","{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
468,"According to the criminal complaint, Edah kick...","{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
469,"According to the criminal complaint, Edah kick...","{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
511,An advertisement for the product shows a girl ...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
519,An advertisement for the product shows a girl ...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
701,Cruz began by mocking Trump’s reputation for i...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
919,"Behold, My Little Deathwing: Ponywing ...","{'text': '', 'tokens': [], 'allsat': False, 'l...",<|endoftext|>,[],False,-1,-1.0,-1,True,<|endoftext|>
1341,The lawsuits dispute Airbnb's assertion that i...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
1343,The lawsuits dispute Airbnb's assertion that i...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.
1670,Dotan says the bridge will serve as a runway f...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.<|endoftext|>,[],False,-1,-1.0,-1,True,.<|endoftext|>
2234,And for those of you who are happily and comfo...,"{'text': '', 'tokens': [], 'allsat': False, 'l...",.,[],False,-1,-1.0,-1,True,.

In [178]:
outputs=pd.read_json('outputs/toxicity/mlm-reranking/roberta-base-jigsaw-toxicity-classifier-with-gpt2-large-embeds/mlm-beamsearch-v0-word-nps5-k10-beam5-allsat_primary-toxic-to-nontoxic-grad_norm-wj9ww99a/outputs_epsilon0.75.txt',
            lines=True)

In [179]:
## unravel
outputs=outputs.explode('generations')

outputs.shape

outputs['prompt1']=outputs['prompt'].apply(lambda x: x['text'])

outputs['text']=outputs['generations'].apply(lambda x: x['text'])

gen_dict=outputs['generations'].values[0]

for col in gen_dict.keys():
    outputs[col] = outputs['generations'].apply(lambda x: x.get(col,None))

In [180]:
outputs=outputs.reset_index(drop=True)

In [181]:
outputs=pd.concat([outputs, origin[['origin_text', 'origin_tokens']]], axis=1)
outputs.loc[outputs['weighted_loss']==-1,'text']=outputs.loc[outputs['weighted_loss']==-1,'origin_text']
outputs.loc[outputs['weighted_loss']==-1,'tokens']=outputs.loc[outputs['weighted_loss']==-1,'origin_tokens']

In [182]:
outputs.loc[outputs['weighted_loss']==-1,]

,prompt,generations,prompt1,text,tokens,indices,orig_tokens_at_indices,allsat,losses,weighted_loss,origin_text,origin_tokens
2,{'text': 'Let me just start by saying I hate h...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",Let me just start by saying I hate horse,fetishes: it just makes me want to puke every ...,"[11351, 5614, 25, 340, 655, 1838, 502, 765, 28...",[[]],None,-1,"[86.68377685546875, 0.09785532951354901]",-1.0,fetishes: it just makes me want to puke every ...,"[11351, 5614, 25, 340, 655, 1838, 502, 765, 28..."
3,{'text': 'Let me just start by saying I hate h...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",Let me just start by saying I hate horse,head gelatin and see it as a sort of travelogu...,"[2256, 49084, 290, 766, 340, 355, 257, 3297, 2...",[[]],None,-1,"[102.35472106933594, 0.0034416036214670004]",-1.0,head gelatin and see it as a sort of travelogu...,"[2256, 49084, 290, 766, 340, 355, 257, 3297, 2..."
4,{'text': 'Let me just start by saying I hate h...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",Let me just start by saying I hate horse,-trading (talk).,"[12, 2213, 4980, 357, 16620, 737]",[[]],None,-1,"[20.794334411621094, 0.036267034709453]",-1.0,-trading (talk).,"[12, 2213, 4980, 357, 16620, 737]"
5,{'text': 'Let me just start by saying I hate h...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",Let me just start by saying I hate horse,"riding or vegas' version of live riding, we ha...","[10311, 393, 1569, 22649, 6, 2196, 286, 2107, ...",[[]],None,-1,"[120.89193725585938, 0.012426217086613001]",-1.0,"riding or vegas' version of live riding, we ha...","[10311, 393, 1569, 22649, 6, 2196, 286, 2107, ..."
6,{'text': 'Let me just start by saying I hate h...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",Let me just start by saying I hate horse,-drawn cars.,"[12, 41549, 5006, 13]",[[]],None,-1,"[7.603146553039551, 0.05948494747281]",-1.0,-drawn cars.,"[12, 41549, 5006, 13]"
...,...,...,...,...,...,...,...,...,...,...,...,...
2495,{'text': 'Thousands of protesters turned out i...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",Thousands of protesters turned out in two regi...,Chad – to demand the release of accused gang l...,"[19800, 784, 284, 3512, 262, 2650, 286, 5371, ...",[[]],None,-1,"[57.6293830871582, 0.08012823760509401]",-1.0,Chad – to demand the release of accused gang l...,"[19800, 784, 284, 3512, 262, 2650, 286, 5371, ..."
2496,{'text': 'Thousands of protesters turned out i...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",Thousands of protesters turned out in two regi...,"Thrace – in the few days preceding Easter, in ...","[16283, 558, 784, 287, 262, 1178, 1528, 18148,...",[[]],None,-1,"[59.40013885498047, 0.0007406114018520001]",-1.0,"Thrace – in the few days preceding Easter, in ...","[16283, 558, 784, 287, 262, 1178, 1528, 18148,..."
2497,{'text': 'Thousands of protesters turned out i...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",Thousands of protesters turned out in two regi...,the Peloponnese – shouting slogans demanding a...,"[262, 12903, 404, 261, 2516, 68, 784, 19642, 3...",[[]],None,-1,"[75.84547424316406, 0.008668531663715002]",-1.0,the Peloponnese – shouting slogans demanding a...,"[262, 12903, 404, 261, 2516, 68, 784, 19642, 3..."
2498,{'text': 'Thousands of protesters turned out i...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",Thousands of protesters turned out in two regi...,Odessa – on Sunday for a second day of rallies...,"[10529, 21411, 784, 319, 3502, 329, 257, 1218,...",[[]],None,-1,"[36.675865173339844, 0.003172961296513]",-1.0,Odessa – on Sunday for a second day of rallies...,"[10529, 21411, 784, 319, 3502, 329, 257, 1218,..."
2499,{'text': 'Thousands of protesters turned out i...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",Thousands of protesters turned out in two regi...,Sidi Bouzid – in protest against the governmen...,"[15686, 72, 14551, 89, 312, 784, 287, 5402, 10...",[[]],None,-1,"[22.785173416137695, 0.0048744892701500005]",-1.0,Sidi Bouzid – in protest against the governmen...,"[15686, 72, 14551, 89, 312, 784, 287, 5402, 10..."

In [183]:
outputs['generations'].values[0].keys()

dict_keys(['text', 'tokens', 'indices', 'orig_tokens_at_indices', 'allsat', 'losses', 'weighted_loss'])

In [184]:
outputs['generations1']=None

In [185]:
for i, row in outputs.iterrows():

    outputs.loc[i, 'generations1'] = [{'text': row['text'],
                           'tokens': row['tokens'],
                           'indices': row['indices'],
                           'orig_tokens_at_indices': row['orig_tokens_at_indices'],
                           'allsat': row['allsat'],
                           'losses': row['losses'],
                           'weighted_loss': row['weighted_loss']}]

In [187]:
outputs = outputs.groupby('prompt1')['generations1'].agg(lambda x: sum(x, [])).reset_index()

In [188]:
outputs0=pd.read_json('outputs/toxicity/mlm-reranking/roberta-base-jigsaw-toxicity-classifier-with-gpt2-large-embeds/mlm-beamsearch-v0-word-nps5-k10-beam5-allsat_primary-toxic-to-nontoxic-grad_norm-wj9ww99a/outputs_epsilon0.75.txt',
            lines=True)
outputs0['prompt1']=outputs0['prompt'].apply(lambda x: x['text'])

In [ ]:
outputs=pd.merge(outputs, outputs0[['prompt','prompt1']], left_on='prompt1', right_on='prompt1')

outputs = outputs.rename(columns={'generations1': 'generations'})
outputs = outputs[['prompt', 'generations']].copy()

In [198]:
outputs.to_json('outputs/toxicity/mlm-reranking/roberta-base-jigsaw-toxicity-classifier-with-gpt2-large-embeds/mlm-beamsearch-v0-word-nps5-k10-beam5-allsat_primary-toxic-to-nontoxic-grad_norm-wj9ww99a/outputs_epsilon0.75_filled.txt',
            lines=True, orient='records')

In [196]:
outputs

,prompt,generations
0,"{'text': '""I don’t want them to leave, but the...",[{'text': 'stopping me. They have nothing to d...
1,"{'text': '""I don’t want youthful marriages, th...",[{'text': 'should stay in his bedroom with ope...
2,"{'text': '""I've had families come to me over t...","[{'text': 'years for my Jewish dinner,"" he sai..."
3,"{'text': '""No quarterback should be offended,""...","[{'text': 'The Miami Herald. ""No one is going ..."
4,"{'text': '""Stop the indoctrination,"" say the o...","[{'text': 'city government.', 'tokens': [1748,..."
...,...,...
245,{'text': '“The Lemonade singer also put the sp...,[{'text': ''s Video Music Awards in January. ...
246,"{'text': '“We can have a beautiful, shiny brid...",[{'text': 'the Grand Canal for a week long com...
247,"{'text': '“We may have only a sterile, secular...","[{'text': 'nothing like the culture of Jesus, ..."
248,"{'text': '“When I graduate with a PhD, I won’t...",[{'text': 'get started.‡ And I literally stil...
249,{'text': '“Wouldn’t you love to see one of the...,"[{'text': ' flag, to say, 'If that man of them..."

In [92]:
outputs=pd.read_json('outputs/toxicity/mlm-reranking/roberta-base-jigsaw-toxicity-classifier-with-gpt2-large-embeds-energy-training/mlm-beamsearch-v0-word-nps5-k10-beam5-allsat_primary-toxic-to-nontoxic-grad_norm-i11w83tg/outputs_epsilon0.75.txt',
            lines=True)

In [93]:
## unravel
outputs=outputs.explode('generations')

outputs.shape

outputs['prompt']=outputs['prompt'].apply(lambda x: x['text'])

outputs['text']=outputs['generations'].apply(lambda x: x['text'])

gen_dict=outputs['generations'].values[0]

for col in gen_dict.keys():
    outputs[col] = outputs['generations'].apply(lambda x: x.get(col,None))

In [94]:
outputs=outputs.reset_index(drop=True)

In [95]:
outputs.loc[outputs['weighted_loss']==-1,]

,prompt,generations,text,tokens,indices,orig_tokens_at_indices,allsat,losses,weighted_loss
3,Let me just start by saying I hate horse,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[102.35472106933594, 0.020356545224785003]",-1.0
4,Let me just start by saying I hate horse,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[20.794334411621094, 0.100537709891796]",-1.0
5,Let me just start by saying I hate horse,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[120.89193725585938, 0.012789840810000001]",-1.0
6,Let me just start by saying I hate horse,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[7.603146553039551, 0.062420517206192]",-1.0
7,Let me just start by saying I hate horse,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[78.08222961425781, 0.1730537712574]",-1.0
...,...,...,...,...,...,...,...,...,...
2495,Thousands of protesters turned out in two regi...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[57.6293830871582, 0.043240942060947]",-1.0
2496,Thousands of protesters turned out in two regi...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[59.40013885498047, 0.017410656437277003]",-1.0
2497,Thousands of protesters turned out in two regi...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[75.84547424316406, 0.008920224383473]",-1.0
2498,Thousands of protesters turned out in two regi...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[36.675865173339844, 0.025409564375877002]",-1.0
2499,Thousands of protesters turned out in two regi...,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[22.785173416137695, 0.003319588722661]",-1.0

In [36]:
with open('data/formality/GYAFC_Corpus/Entertainment_Music/test/informal', 'r') as f:
    origin = [line.rstrip('\n') for line in f.readlines()]
origin=pd.DataFrame({'origin_text':origin})
# ## unravel
# origin=origin.explode('generations')

# origin.shape

# origin['prompt']=origin['prompt'].apply(lambda x: x['text'])

# origin['text']=origin['generations'].apply(lambda x: x['text'])

# gen_dict=origin['generations'].values[0]

# for col in gen_dict.keys():
#     origin[col] = origin['generations'].apply(lambda x: x[col])

# origin=origin.reset_index(drop=True)

# origin=origin.rename(columns={'text':'origin_text'})

In [ ]:
outputs=pd.read_json('outputs/formality/roberta-base-pt16-formality-classifier-with-gpt2-large-embeds/gbi-word-netps3-nls1-os20-es4-allsat-informal-to-formal-attention-51vyyo2c/outputs_epsilon-3.txt',
            lines=True)

## unravel
outputs=outputs.explode('generations')

outputs.shape

outputs['prompt']=outputs['prompt'].apply(lambda x: x['text'])

outputs['text']=outputs['generations'].apply(lambda x: x['text'])

gen_dict=outputs['generations'].values[0]

for col in gen_dict.keys():
    outputs[col] = outputs['generations'].apply(lambda x: x[col])

outputs=outputs.reset_index(drop=True)

In [41]:
outputs=pd.concat([outputs, origin[['origin_text']]], axis=1)

In [44]:
outputs.loc[outputs['text']=='',]

Empty DataFrame
Columns: [prompt, generations, text, tokens, allsat, losses, weighted_loss, repeat_count, mucoco, origin_text]
Index: []

In [42]:
outputs.loc[outputs['text']=='','text']=outputs.loc[outputs['text']=='','origin_text']

In [43]:
outputs.loc[outputs['weighted_loss']==-1,]

Empty DataFrame
Columns: [prompt, generations, text, tokens, allsat, losses, weighted_loss, repeat_count, mucoco, origin_text]
Index: []

In [45]:
outputs=pd.read_json('outputs/formality/roberta-base-pt16-formality-classifier-with-gpt2-large-embeds-energy-training/gbi-word-netps3-nls1-os20-es4-allsat-informal-to-formal-attention-y4l0jmmu/outputs_epsilon-3.txt',
            lines=True)

In [46]:
## unravel
outputs=outputs.explode('generations')

outputs.shape

outputs['prompt']=outputs['prompt'].apply(lambda x: x['text'])

outputs['text']=outputs['generations'].apply(lambda x: x['text'])

gen_dict=outputs['generations'].values[0]

for col in gen_dict.keys():
    outputs[col] = outputs['generations'].apply(lambda x: x[col])

In [47]:
outputs=outputs.reset_index(drop=True)

In [48]:
outputs=pd.concat([outputs, origin[['origin_text']]], axis=1)

In [49]:
outputs.loc[outputs['text']=='',]

Empty DataFrame
Columns: [prompt, generations, text, tokens, allsat, losses, weighted_loss, repeat_count, mucoco, origin_text]
Index: []

In [50]:
outputs.loc[outputs['text']=='','text']=outputs.loc[outputs['text']=='','origin_text']

In [51]:
outputs.loc[outputs['weighted_loss']==-1,]

Empty DataFrame
Columns: [prompt, generations, text, tokens, allsat, losses, weighted_loss, repeat_count, mucoco, origin_text]
Index: []

In [77]:
outputs=pd.read_json('outputs/formality/mlm-reranking/roberta-base-pt16-formality-classifier-with-gpt2-large-embeds/mlm-beamsearch-v0-word-nps5-k10-beam5-allsat_primary-informal-to-formal-grad_norm-tsm4ckdh/outputs_epsilon0.75.txt',
            lines=True)

## unravel
outputs=outputs.explode('generations')

outputs.shape

outputs['prompt']=outputs['prompt'].apply(lambda x: x['text'])

outputs['text']=outputs['generations'].apply(lambda x: x['text'])

gen_dict=outputs['generations'].values[0]

for col in gen_dict.keys():
    outputs[col] = outputs['generations'].apply(lambda x: x[col])

In [80]:
outputs.loc[outputs['text']=='',]

Empty DataFrame
Columns: [prompt, generations, text, tokens, indices, orig_tokens_at_indices, allsat, losses, weighted_loss]
Index: []

In [83]:
outputs=pd.read_json('outputs/formality/mlm-reranking/roberta-base-pt16-formality-classifier-with-gpt2-large-embeds-energy-training/mlm-beamsearch-v0-word-nps5-k10-beam5-allsat_primary-informal-to-formal-grad_norm-ddtoxbcr/outputs_epsilon0.75.txt',
            lines=True)

## unravel
outputs=outputs.explode('generations')

outputs.shape

outputs['prompt']=outputs['prompt'].apply(lambda x: x['text'])

outputs['text']=outputs['generations'].apply(lambda x: x['text'])

gen_dict=outputs['generations'].values[0]

for col in gen_dict.keys():
    outputs[col] = outputs['generations'].apply(lambda x: x[col])

In [84]:
outputs.loc[outputs['text']=='',]

Empty DataFrame
Columns: [prompt, generations, text, tokens, indices, orig_tokens_at_indices, allsat, losses, weighted_loss]
Index: []

In [2]:
origin=pd.read_json('new_module/data/sentiment/outputs.txt.init.jsonl', lines=True)

## unravel
origin=origin.explode('generations')

origin.shape

origin['prompt']=origin['prompt'].apply(lambda x: x['text'])

origin['text']=origin['generations'].apply(lambda x: x['text'])

gen_dict=origin['generations'].values[0]

for col in gen_dict.keys():
    origin[col] = origin['generations'].apply(lambda x: x[col])

origin=origin.reset_index(drop=True)

origin=origin.rename(columns={'text':'origin_text'})

In [3]:
outputs=pd.read_json('outputs/sentiment/roberta-base-yelp-sentiment-classifier-with-gpt2-large-embeds/gbi-word-netps-1-nls-1-os200-es40-allsat-negative-to-positive-attention-ni3j72ae/outputs_epsilon-3.txt',
            lines=True)

In [4]:
## unravel
outputs=outputs.explode('generations')

outputs.shape

outputs['prompt']=outputs['prompt'].apply(lambda x: x['text'])

outputs['text']=outputs['generations'].apply(lambda x: x['text'])

gen_dict=outputs['generations'].values[0]

for col in gen_dict.keys():
    outputs[col] = outputs['generations'].apply(lambda x: x[col])

In [5]:
outputs=outputs.reset_index(drop=True)

In [6]:
outputs=pd.concat([outputs, origin[['origin_text']]], axis=1)

In [57]:
outputs.loc[outputs['text']=='',]

Empty DataFrame
Columns: [prompt, generations, text, tokens, allsat, losses, weighted_loss, repeat_count, mucoco, origin_text]
Index: []

In [58]:
outputs.loc[outputs['text']=='','text']=outputs.loc[outputs['text']=='','origin_text']

In [59]:
outputs.loc[outputs['weighted_loss']==-1,]

Empty DataFrame
Columns: [prompt, generations, text, tokens, allsat, losses, weighted_loss, repeat_count, mucoco, origin_text]
Index: []

In [8]:
outputs=pd.read_json('outputs/sentiment/roberta-base-yelp-sentiment-classifier-with-gpt2-large-embeds-energy-training/gbi-word-netps-1-nls-1-os200-es40-allsat-negative-to-positive-attention-1hiw01es/outputs_epsilon-3.txt',
            lines=True)

In [9]:
## unravel
outputs=outputs.explode('generations')

outputs.shape

outputs['prompt']=outputs['prompt'].apply(lambda x: x['text'])

outputs['text']=outputs['generations'].apply(lambda x: x['text'])

gen_dict=outputs['generations'].values[0]

for col in gen_dict.keys():
    outputs[col] = outputs['generations'].apply(lambda x: x[col])

In [10]:
outputs=outputs.reset_index(drop=True)

In [11]:
outputs=pd.concat([outputs, origin[['origin_text']]], axis=1)

In [64]:
outputs.loc[outputs['text']=='',]

Empty DataFrame
Columns: [prompt, generations, text, tokens, allsat, losses, weighted_loss, repeat_count, mucoco, origin_text]
Index: []

In [65]:
outputs.loc[outputs['text']=='','text']=outputs.loc[outputs['text']=='','origin_text']

In [66]:
outputs.loc[outputs['weighted_loss']==-1,]

Empty DataFrame
Columns: [prompt, generations, text, tokens, allsat, losses, weighted_loss, repeat_count, mucoco, origin_text]
Index: []

In [16]:
outputs=pd.read_json('outputs/sentiment/mlm-reranking/roberta-base-yelp-sentiment-classifier-with-gpt2-large-embeds/mlm-beamsearch-v0-word-nps5-k10-beam5-allsat_primary-negative-to-positive-grad_norm-gahrb4gt/outputs_epsilon0.75.txt',
            lines=True)

In [17]:
## unravel
outputs=outputs.explode('generations')

outputs.shape

outputs['prompt']=outputs['prompt'].apply(lambda x: x['text'])

outputs['text']=outputs['generations'].apply(lambda x: x['text'])

gen_dict=outputs['generations'].values[0]

for col in gen_dict.keys():
    
    outputs[col] = outputs['generations'].apply(lambda x: x.get(col, None))

In [18]:
outputs=outputs.reset_index(drop=True)

In [19]:
outputs=pd.concat([outputs, origin[['origin_text']]], axis=1)

In [20]:
outputs.loc[outputs['text']=='',]

,prompt,generations,text,tokens,indices,orig_tokens_at_indices,allsat,losses,weighted_loss,origin_text
1,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[50.015907287597656, 0.0018468719208610002]",-1.0,", the Metaphysical Systems department of the U..."
4,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[97.76002502441406, 0.12838825583457902]",-1.0,", a small group of geeks developed methods to ..."
6,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[54.46814727783203, 0.10594361275434401]",-1.0,there was one small town called Excelsior... I...
7,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[50.22785949707031, 0.23322175443172402]",-1.0,", gods smithied their own weapons and armor fr..."
8,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[87.54047393798828, 0.11287005245685501]",-1.0,", there was Riku Plutia.\n\nOnly thing was, du..."
...,...,...,...,...,...,...,...,...,...,...
292,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[92.55097961425781, 0.208538994193077]",-1.0,It was not because the gods had heard my praye...
293,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[75.03350830078125, 0.183982595801353]",-1.0,"When Shimon Tamir was four years old, his fath..."
295,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[91.3620834350586, 0.038271021097898004]",-1.0,A group of travelers hopes to save a converted...
296,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[18.37665367126465, 0.062449745833873006]",-1.0,It is spring.
298,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[159.52764892578125, 0.072996921837329]",-1.0,"The English, still accustomed to the bargain o..."

In [75]:
outputs.loc[outputs['text']=='','text']=outputs.loc[outputs['text']=='','origin_text']

In [76]:
outputs.loc[outputs['weighted_loss']==-1,]

,prompt,generations,text,tokens,indices,orig_tokens_at_indices,allsat,losses,weighted_loss,origin_text
1,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",", the Metaphysical Systems department of the U...",[],[[]],None,-1,"[50.015907287597656, 0.0018468719208610002]",-1.0,", the Metaphysical Systems department of the U..."
4,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",", a small group of geeks developed methods to ...",[],[[]],None,-1,"[97.76002502441406, 0.12838825583457902]",-1.0,", a small group of geeks developed methods to ..."
6,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",there was one small town called Excelsior... I...,[],[[]],None,-1,"[54.46814727783203, 0.10594361275434401]",-1.0,there was one small town called Excelsior... I...
7,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",", gods smithied their own weapons and armor fr...",[],[[]],None,-1,"[50.22785949707031, 0.23322175443172402]",-1.0,", gods smithied their own weapons and armor fr..."
8,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",", there was Riku Plutia.\n\nOnly thing was, du...",[],[[]],None,-1,"[87.54047393798828, 0.11287005245685501]",-1.0,", there was Riku Plutia.\n\nOnly thing was, du..."
...,...,...,...,...,...,...,...,...,...,...
292,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",It was not because the gods had heard my praye...,[],[[]],None,-1,"[92.55097961425781, 0.208538994193077]",-1.0,It was not because the gods had heard my praye...
293,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...","When Shimon Tamir was four years old, his fath...",[],[[]],None,-1,"[75.03350830078125, 0.183982595801353]",-1.0,"When Shimon Tamir was four years old, his fath..."
295,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",A group of travelers hopes to save a converted...,[],[[]],None,-1,"[91.3620834350586, 0.038271021097898004]",-1.0,A group of travelers hopes to save a converted...
296,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",It is spring.,[],[[]],None,-1,"[18.37665367126465, 0.062449745833873006]",-1.0,It is spring.
298,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...","The English, still accustomed to the bargain o...",[],[[]],None,-1,"[159.52764892578125, 0.072996921837329]",-1.0,"The English, still accustomed to the bargain o..."

In [21]:
outputs_clsf=outputs.copy()

In [22]:
outputs=pd.read_json('outputs/sentiment/mlm-reranking/roberta-base-yelp-sentiment-classifier-with-gpt2-large-embeds-energy-training/mlm-beamsearch-v0-word-nps5-k10-beam5-allsat_primary-negative-to-positive-grad_norm-omhz1rr1/outputs_epsilon0.75.txt',
            lines=True)

In [23]:
## unravel
outputs=outputs.explode('generations')

outputs.shape

outputs['prompt']=outputs['prompt'].apply(lambda x: x['text'])

outputs['text']=outputs['generations'].apply(lambda x: x['text'])

gen_dict=outputs['generations'].values[0]

for col in gen_dict.keys():
    
    outputs[col] = outputs['generations'].apply(lambda x: x.get(col, None))

In [24]:
outputs=outputs.reset_index(drop=True)

In [25]:
outputs=pd.concat([outputs, origin[['origin_text']]], axis=1)

In [26]:
outputs.loc[outputs['text']=='',]

,prompt,generations,text,tokens,indices,orig_tokens_at_indices,allsat,losses,weighted_loss,origin_text
1,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[50.015907287597656, 0.096410766243934]",-1.0,", the Metaphysical Systems department of the U..."
4,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[97.76002502441406, 0.08981584012508301]",-1.0,", a small group of geeks developed methods to ..."
6,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[54.46814727783203, 0.09246344864368401]",-1.0,there was one small town called Excelsior... I...
7,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[50.22785949707031, 0.033290460705757]",-1.0,", gods smithied their own weapons and armor fr..."
8,Once upon a time,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[87.54047393798828, 0.129185810685157]",-1.0,", there was Riku Plutia.\n\nOnly thing was, du..."
...,...,...,...,...,...,...,...,...,...,...
290,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[142.15829467773438, 0.07137002050876601]",-1.0,Although some American industries were thrivin...
291,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[66.5772705078125, 0.10536270588636301]",-1.0,The nations that have freed the slaves of othe...
292,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[92.55097961425781, 0.21010313928127203]",-1.0,It was not because the gods had heard my praye...
296,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[18.37665367126465, 0.13988517224788602]",-1.0,It is spring.
298,The year is 1910.,"{'text': '', 'tokens': [], 'indices': [[]], 'a...",,[],[[]],None,-1,"[159.52764892578125, 0.040928609669208006]",-1.0,"The English, still accustomed to the bargain o..."

In [27]:
outputs_em=outputs.copy()

In [31]:
compr=pd.merge(outputs_em[['prompt','origin_text','text', 'allsat']],outputs_clsf[['prompt','origin_text','text','allsat']],on=['prompt','origin_text'],suffixes=['_em','_clsf'])

In [33]:
compr.loc[(compr['allsat_em']!=-1) & (compr['allsat_clsf']!=-1)].shape

(113, 6)

In [34]:
compr.loc[(compr['allsat_em']!=-1)].shape

(134, 6)

In [35]:
compr.loc[(compr['allsat_clsf']!=-1)].shape

(154, 6)